apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ cat "app:" .Chart.Name | nindent 4 }}
  name: gcp-pubsub-dispatcher
  namespace: knative-eventing
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    clusterChannelProvisioner: gcp-pubsub
    role: dispatcher
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
  type: {{ .Values.gcpPubsubDispatcher.type }}
