apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ cat "app:" .Chart.Name | nindent 4 }}
  name: in-memory-channel-dispatcher
  namespace: knative-eventing
spec:
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
