apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ "addonmanager.kubernetes.io/mode: Reconcile" | nindent 4 }} {{ cat "app: elasticsearch-logging," .Chart.Name | nindent 4 }} {{ "kubernetes.io/cluster-service: true" | nindent 4 }}
  name: elasticsearch-logging
rules:
- apiGroups:
  - ''
  resources:
  - services
  - namespaces
  - endpoints
  verbs:
  - get
spec:
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
