apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ "addonmanager.kubernetes.io/mode: Reconcile" | nindent 4 }} {{ cat "app: elasticsearch-logging," .Chart.Name | nindent 4 }} {{ "kubernetes.io/cluster-service: true" | nindent 4 }} {{ "kubernetes.io/name: Elasticsearch" | nindent 4 }}
  name: elasticsearch-logging
  namespace: knative-monitoring
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    app: elasticsearch-logging
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
