apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ cat "app: node-exporter," .Chart.Name | nindent 4 }}
  name: node-exporter
  namespace: knative-monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: {{ .Values.nodeExporter.kubeRbacProxy.https.hostPort }}
    protocol: TCP
  selector:
    app: node-exporter
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
  type: {{ .Values.nodeExporter.type }}
