apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ "serving.knative.dev/release: devel" | nindent 4 }} {{ cat "app:" .Chart.Name | nindent 4 }}
  name: prometheus-system
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-system
spec:
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
subjects:
- kind: ServiceAccount
  name: prometheus-system
  namespace: knative-monitoring
