apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ "serving.knative.dev/release: devel" | nindent 4 }} {{ cat "app:" .Chart.Name | nindent 4 }}
  name: prometheus-system-np
  namespace: knative-monitoring
spec:
  ports:
  - port: 8080
    targetPort: 9090
  selector:
    app: prometheus
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
  type: {{ .Values.prometheusSystemNp.type }}
