apiVersion: v1
kind: Service
metadata:
  labels: {{ include "labels" . | nindent 4 }} {{ "serving.knative.dev/release: devel" | nindent 4 }} {{ cat "app:" .Chart.Name | nindent 4 }}
  name: zipkin
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 9411
  selector:
    app: zipkin
  template:
    metadata:
      labels: {{ include "noVersionlabels" . | nindent 8 }} {{ cat "app:" .Chart.Name | nindent 8 }}
